export enum HOOK_TYPE {
  ACTION_EXECUTE = "action.execute",
  ACTION_LOCATION = "action.location",
  ACTION_QUERY = "action.query",
  GUEST_GENERATION = "guest.generation",
  INTERVAL_DAY = "interval.day",
  INTERVAL_TICK = "interval.tick",
  MAP_CHANGE = "map.change",
  MAP_CHANGED = "map.changed",
  MAP_SAVE = "map.save",
  NETWORK_ACTION = "network.action",
  NETWORK_AUTHENTICATE = "network.authenticate",
  NETWORK_CHAT = "network.chat",
  NETWORK_JOIN = "network.join",
  NETWORK_LEAVE = "network.leave",
  RIDE_RATINGS_CALCULATE = "ride.ratings.calculate",
  VEHICLE_CRASH = "vehicle.crash",
}

export const {
  ACTION_QUERY,
  ACTION_EXECUTE,
  INTERVAL_TICK,
  INTERVAL_DAY,
  NETWORK_CHAT,
  NETWORK_AUTHENTICATE,
  NETWORK_ACTION,
  NETWORK_JOIN,
  NETWORK_LEAVE,
  RIDE_RATINGS_CALCULATE,
  ACTION_LOCATION,
  VEHICLE_CRASH,
  MAP_CHANGE,
  MAP_CHANGED,
  MAP_SAVE,
  GUEST_GENERATION,
} = HOOK_TYPE;
