export enum ACTION_TYPE {
  BALLOON_PRESS = "balloonpress",
  BANNER_PLACE = "bannerplace",
  BANNER_REMOVE = "bannerremove",
  BANNER_SET_COLOUR = "bannersetcolour",
  BANNER_SET_NAME = "bannersetname",
  BANNER_SET_STYLE = "bannersetstyle",
  CHEAT_SET = "cheatset",
  CLEAR_SCENERY = "clearscenery",
  CLIMATE_SET = "climateset",
  FOOTPATH_ADDITION_PLACE = "footpathadditionplace",
  FOOTPATH_ADDITION_REMOVE = "footpathadditionremove",
  FOOTPATH_PLACE = "footpathplace",
  FOOTPATH_LAYOUT_PLACE = "footpathlayoutplace",
  FOOTPATH_REMOVE = "footpathremove",
  GUEST_SET_FLAG = "guestsetflags",
  GUEST_SET_NAME = "guestsetname",
  LAND_BUY_RIGHTS = "landbuyrights",
  LAND_LOWER = "landlower",
  LAND_RAISE = "landraise",
  LAND_SET_HEIGHT = "landsetheight",
  LAND_SET_RIGHTS = "landsetrights",
  LAND_SMOOTH = "landsmooth",
  LARGE_SCENERY_PLACE = "largesceneryplace",
  LARGE_SCENERY_REMOVE = "largesceneryremove",
  LARGE_SCENERY_SET_COLOUR = "largescenerysetcolour",
  LOAD_OR_QUIT = "loadorquit",
  MAP_CHANGE_SIZE = "mapchangesize",
  MAZE_PLACE_TRACK = "mazeplacetrack",
  MAZE_SET_TRACK = "mazesettrack",
  NETWORK_MODIFY_GROUP = "networkmodifygroup",
  PARK_ENTRANCE_PLACE = "parkentranceplace",
  PARK_ENTRANCE_REMOVE = "parkentranceremove",
  PARK_MARKETING = "parkmarketing",
  PARK_SET_DATE = "parksetdate",
  PARK_SET_ENTRANCE_FEE = "parksetentrancefee",
  PARK_SET_LOAN = "parksetloan",
  PARK_SET_NAME = "parksetname",
  PARK_SET_PARAMETER = "parksetparameter",
  PARK_SET_RESEARCH_FUNDING = "parksetresearchfunding",
  PAUSE_TOGGLE = "pausetoggle",
  PEEP_PICKUP = "peeppickup",
  PEEP_SPAWN_PLACE = "peepspawnplace",
  PLAYER_KICK = "playerkick",
  PLAYER_SET_GROUP = "playersetgroup",
  RIDE_CREATE = "ridecreate",
  RIDE_DEMOLISH = "ridedemolish",
  RIDE_ENTRANCE_EXIT_PLACE = "rideentranceexitplace",
  RIDE_ENTRANCE_EXIT_REMOVE = "rideentranceexitremove",
  RIDE_FREEZE_RATING = "ridefreezerating",
  RIDE_SET_APPEARANCE = "ridesetappearance",
  RIDE_SET_COLOUR_SCHEME = "ridesetcolourscheme",
  RIDE_SET_NAME = "ridesetname",
  RIDE_SET_PRICE = "ridesetprice",
  RIDE_SET_SETTING = "ridesetsetting",
  RIDE_SET_STATUS = "ridesetstatus",
  RIDE_SET_VEHICLE = "ridesetvehicle",
  SCENARIO_SET_SETTING = "scenariosetsetting",
  SIGN_SET_NAME = "signsetname",
  SIGN_SET_STYLE = "signsetstyle",
  SMALL_SCENERY_PLACE = "smallsceneryplace",
  SMALL_SCENERY_REMOVE = "smallsceneryremove",
  SMALL_SCENERY_SET_COLOUR = "smallscenerysetcolour",
  STAFF_FIRE = "stafffire",
  STAFF_HIRE = "staffhire",
  STAFF_SET_COLOUR = "staffsetcolour",
  STAFF_SET_COSTUME = "staffsetcostume",
  STAFF_SET_NAME = "staffsetname",
  STAFF_SET_ORDERS = "staffsetorders",
  STAFF_SET_PATROL_AREA = "staffsetpatrolarea",
  SURFACE_SET_STYLE = "surfacesetstyle",
  TILE_MODIFY = "tilemodify",
  TRACK_DESIGN = "trackdesign",
  TRACK_PLACE = "trackplace",
  TRACK_REMOVE = "trackremove",
  TRACK_SET_BRAKE_SPEED = "tracksetbrakespeed",
  WALL_PLACE = "wallplace",
  WALL_REMOVE = "wallremove",
  WALL_SET_COLOUR = "wallsetcolour",
  WATER_LOWER = "waterlower",
  WATER_RAISE = "waterraise",
  WATER_SET_HEIGHT = "watersetheight",
}

export enum EXPENDITURE_TYPE {
  RIDE_CONSTRUCTION = "ride_construction",
  RIDE_RUNNINGCOSTS = "ride_runningcosts",
  LAND_PURCHASE = "land_purchase",
  LANDSCAPING = "landscaping",
  PARK_ENTRANCE_TICKETS = "park_entrance_tickets",
  PARK_RIDE_TICKETS = "park_ride_tickets",
  SHOP_SALES = "shop_sales",
  SHOP_STOCK = "shop_stock",
  FOOD_DRINK_SALES = "food_drink_sales",
  FOOD_DRINK_STOCK = "food_drink_stock",
  WAGES = "wages",
  MARKETING = "marketing",
  RESEARCH = "research",
  INTEREST = "interest",
}

export const {
  BALLOON_PRESS,
  BANNER_PLACE,
  BANNER_REMOVE,
  BANNER_SET_COLOUR,
  BANNER_SET_NAME,
  BANNER_SET_STYLE,
  CHEAT_SET,
  CLEAR_SCENERY,
  CLIMATE_SET,
  FOOTPATH_ADDITION_PLACE,
  FOOTPATH_ADDITION_REMOVE,
  FOOTPATH_PLACE,
  FOOTPATH_LAYOUT_PLACE,
  FOOTPATH_REMOVE,
  GUEST_SET_FLAG,
  GUEST_SET_NAME,
  LAND_BUY_RIGHTS,
  LAND_LOWER,
  LAND_RAISE,
  LAND_SET_HEIGHT,
  LAND_SET_RIGHTS,
  LAND_SMOOTH,
  LARGE_SCENERY_PLACE,
  LARGE_SCENERY_REMOVE,
  LARGE_SCENERY_SET_COLOUR,
  LOAD_OR_QUIT,
  MAP_CHANGE_SIZE,
  MAZE_PLACE_TRACK,
  MAZE_SET_TRACK,
  NETWORK_MODIFY_GROUP,
  PARK_ENTRANCE_PLACE,
  PARK_ENTRANCE_REMOVE,
  PARK_MARKETING,
  PARK_SET_DATE,
  PARK_SET_ENTRANCE_FEE,
  PARK_SET_LOAN,
  PARK_SET_NAME,
  PARK_SET_PARAMETER,
  PARK_SET_RESEARCH_FUNDING,
  PAUSE_TOGGLE,
  PEEP_PICKUP,
  PEEP_SPAWN_PLACE,
  PLAYER_KICK,
  PLAYER_SET_GROUP,
  RIDE_CREATE,
  RIDE_DEMOLISH,
  RIDE_ENTRANCE_EXIT_PLACE,
  RIDE_ENTRANCE_EXIT_REMOVE,
  RIDE_FREEZE_RATING,
  RIDE_SET_APPEARANCE,
  RIDE_SET_COLOUR_SCHEME,
  RIDE_SET_NAME,
  RIDE_SET_PRICE,
  RIDE_SET_SETTING,
  RIDE_SET_STATUS,
  RIDE_SET_VEHICLE,
  SCENARIO_SET_SETTING,
  SIGN_SET_NAME,
  SIGN_SET_STYLE,
  SMALL_SCENERY_PLACE,
  SMALL_SCENERY_REMOVE,
  SMALL_SCENERY_SET_COLOUR,
  STAFF_FIRE,
  STAFF_HIRE,
  STAFF_SET_COLOUR,
  STAFF_SET_COSTUME,
  STAFF_SET_NAME,
  STAFF_SET_ORDERS,
  STAFF_SET_PATROL_AREA,
  SURFACE_SET_STYLE,
  TILE_MODIFY,
  TRACK_DESIGN,
  TRACK_PLACE,
  TRACK_REMOVE,
  TRACK_SET_BRAKE_SPEED,
  WALL_PLACE,
  WALL_REMOVE,
  WALL_SET_COLOUR,
  WATER_LOWER,
  WATER_RAISE,
  WATER_SET_HEIGHT,
} = ACTION_TYPE;
