export enum TILE_ELEMENT_TYPE {
    SURFACE = "surface",
    FOOTPATH = "footpath",
    TRACK = "track",
    SMALL_SCENERY = "small_scenery",
    WALL = "wall",
    ENTRANCE = "entrance",
    LARGE_SCENERY = "large_scenery",
    BANNER = "banner"
}

export enum ACTION_TYPE {
    BALLOON_PRESS = "balloonpress",
    BANNER_PLACE = "bannerplace",
    BANNER_REMOVE = "bannerremove",
    BANNER_SET_COLOUR = "bannersetcolour",
    BANNER_SET_NAME = "bannersetname",
    BANNER_SET_STYLE = "bannersetstyle",
    SET_CHEAT = "setcheat",
    CLEAR_SCENERY = "clearscenery",
    CLIMATE_SET = "climateset",
    FOOTPATH_ADDITION_PLACE = "footpathadditionplace",
    FOOTPATH_ADDITION_REMOVE = "footpathadditionremove",
    FOOTPATH_PLACE = "footpathplace",
    FOOTPATH_LAYOUT_PLACE = "footpathlayoutplace",
    FOOTPATH_REMOVE = "footpathremove",
    GUEST_SET_FLAG = "guestsetflags",
    GUEST_SET_NAME = "guestsetname",
    LAND_BUY_RIGHTS = "landbuyrights",
    LAND_LOWER = "landlower",
    LAND_RAISE = "landraise",
    LAND_SET_HEIGHT = "landsetheight",
    LAND_SET_RIGHTS = "landsetrights",
    LAND_SMOOTH = "landsmooth",
    LARGE_SCENERY_PLACE = "largesceneryplace",
    LARGE_SCENERY_REMOVE = "largesceneryremove",
    LARGE_SCENERY_SET_COLOUR = "largescenerysetcolour",
    LOAD_OR_QUIT = "loadorquit",
    MAP_CHANGE_SIZE = "mapchangesize",
    MAZE_PLACE_TRACK = "mazeplacetrack",
    MAZE_SET_TRACK = "mazesettrack",
    NETWORK_MODIFY_GROUP = "networkmodifygroup",
    PARK_ENTRANCE_PLACE = "parkentranceplace",
    PARK_ENTRANCE_REMOVE = "parkentranceremove",
    PARK_MARKETING = "parkmarketing",
    PARK_SET_DATE = "parksetdate",
    PARK_SET_ENTRANCE_FEE = "parksetentrancefee",
    PARK_SET_LOAN = "parksetloan",
    PARK_SET_NAME = "parksetname",
    PARK_SET_PARAMETER = "parksetparameter",
    PARK_SET_RESEARCH_FUNDING = "parksetresearchfunding",
    PAUSE_TOGGLE = "pausetoggle",
    PEEP_PICKUP = "peeppickup",
    PEEP_SPAWN_PLACE = "peepspawnplace",
    PLAYER_KICK = "playerkick",
    PLAYER_SET_GROUP = "playersetgroup",
    RIDE_CREATE = "ridecreate",
    RIDE_DEMOLISH = "ridedemolish",
    RIDE_ENTRANCE_EXIT_PLACE = "rideentranceexitplace",
    RIDE_ENTRANCE_EXIT_REMOVE = "rideentranceexitremove",
    RIDE_FREEZE_RATING = "ridefreezerating",
    RIDE_SET_APPEARANCE = "ridesetappearance",
    RIDE_SET_COLOUR_SCHEME = "ridesetcolourscheme",
    RIDE_SET_NAME = "ridesetname",
    RIDE_SET_PRICE = "ridesetprice",
    RIDE_SET_SETTING = "ridesetsetting",
    RIDE_SET_STATUS = "ridesetstatus",
    RIDE_SET_VEHICLE = "ridesetvehicle",
    SCENARIO_SETTING = "scenariosetsetting",
    SIGN_SET_NAME = "signsetname",
    SIGN_SET_STYLE = "signsetstyle",
    SMALL_SCENERY_PLACE = "smallsceneryplace",
    SMALL_SCENERY_REMOVE = "smallsceneryremove",
    SMALL_SCENERY_SET_COLOUR = "smallscenerysetcolour",
    STAFF_FIRE = "stafffire",
    STAFF_HIRE = "staffhire",
    STAFF_SET_COLOUR = "staffsetcolour",
    STAFF_SET_COSTUME = "staffsetcostume",
    STAFF_SET_NAME = "staffsetname",
    STAFF_SET_ORDERS = "staffsetorders",
    STAFF_SET_PATROL_AREA = "staffsetpatrolarea",
    SURFACE_SET_STYLE = "surfacesetstyle",
    TILE_MODIFY = "tilemodify",
    TRACK_DESIGN = "trackdesign",
    TRACK_PLACE = "trackplace",
    TRACK_REMOVE = "trackremove",
    TRACK_SET_BRAKE_SPEED = "tracksetbrakespeed",
    WALL_PLACE = "wallplace",
    WALL_REMOVE = "wallremove",
    WALL_SET_COLOUR = "wallsetcolour",
    WATER_LOWER = "waterlower",
    WATER_RAISE = "waterraise",
    WATER_SET_HEIGHT = "watersetheight",
}

export enum CHEAT_TYPE {
    SANDBOX_MODE,
    DISABLE_CLEARANCE_CHECKS,
    DISABLE_SUPPORT_LIMITS,
    SHOW_ALL_OPERATING_MODES,
    SHOW_VEHICLES_FROM_OTHER_TRACK_TYPES,
    DISABLE_TRAIN_LENGTH_LIMIT,
    ENABLE_CHAIN_LFT_ON_ALL_TRACK,
    FAST_LIFT_HILL,
    DISABLE_BRAKES_FAILURE,
    DISABLE_ALL_BREAKDOWNS,
    UNLOCK_ALL_PRICES,
    BUILD_IN_PAUSE_MODE,
    IGNORE_RIDE_INTENSITY,
    DISABLE_VANDALISM,
    DISABLE_LITTERING,
    NO_MONEY,
    ADD_MONEY,
    SET_MONEY,
    CLEAR_LOAN,
    SET_GUEST_PARAMETER,
    GENERATE_GUESTS,
    REMOVE_ALL_GUESTS,
    GIVE_ALL_GUESTS,
    SET_GRASS_LENGTH,
    WATER_PLANTS,
    DISABLE_PLANT_AGING,
    FIX_VANDALISM,
    REMOVE_LITTER,
    SET_STAFF_SPEED,
    RENEW_RIDES,
    MAKE_DESTRUCTIBLE,
    FIX_RIDES,
    RESET_CRASH_STATUS,
    TEN_MINUTE_INSPECTIONS,
    WIN_SCENARIO,
    FORCE_WEATHER,
    FREEZE_WEATHER,
    OPEN_CLOSE_PARK,
    HAVE_FUN,
    SET_FORCED_PARK_RATING,
    NEVER_ENDING_MARKETING,
    ALLOW_ARBITRARY_RIDE_TYPE_CHANGES,
    OWN_ALL_LAND,
    DISABLE_RIDE_VALUE_AGING,
    IGNORE_RESEARCH_STATUS,
    ENABLE_ALL_DRAWABLE_TRACK_PIECES,
    CREATE_DUCKS,
    REMOVE_DUCKS,
    ALLOW_TRACK_PLACE_INVALID_HEIGHTS,
    // Removed; this dummy exists only for deserialization parks that had it saved
    NO_CAP_ON_QUEUE_LENGTH_DUMMY,
    ALLOW_REGULAR_PATH_AS_QUEUE,
    ALLOW_SPECIAL_COLOUR_SCHEMES,
    COUNT
}